version: "3.9"

services:
  redux-from-scratch:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
      FAST_REFRESH: "false"
    stdin_open: true
