version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.18.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm run test        
      - save_cache:
          paths:
            - "dependencies"
          key: dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
