version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.18.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules 
          key: dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Run tests
          command: npm run test        
