version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.18.1
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Log current branch and code files
          command: |
            echo listing files
            ls -al
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: circleci/node:14.18.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
