version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.18.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}

  test:
    docker:
      - image: circleci/node:14.18.1
    steps:
      - run:
          name: Run tests
          command: npm run test
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
