version: 2.1
orbs:
  slack: circleci/slack@4.0

jobs:
  build:
    docker:
      - image: circleci/node:14.18.1
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm run test
      # In the event the deployment has failed, send a notifications
      - slack/notify:
          event: fail
          template: basic_fail_1
      # When there is a successful deployment, send a notification
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          context:
            - slack-secrets
