version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.18.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-
      - run:
          npm install
          npm run test
