version: 2.1
orbs:
  slack: circleci/slack@4.0
jobs:
  # This "test" job will run on every commit (as per our workflow)
  # We are ok with no notifications sent for this job.
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "test my app"
  # This "deploy" job will only run on a tagged commit (as per our workflow)
  # We want to be alerted if this job fails and also when it succeeds.
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "deploy my app"
      # In the event the deployment has failed, alert the engineering team
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: "@EngineeringTeam"
      # When there is a successful deployment, send a notification with a different template.
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
workflows:
  test-and-deploy:
    jobs:
      # We want the test job to run on all commits, so we will list it with no filters.
      - test
      # The deploy job will continue once the workflow has been manually approved.
      - deploy:
          context:
            - slack-secrets
          requires:
            - test
